# Generated by Django 5.0.1 on 2024-01-12 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locataires", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Versement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paiement", models.DateField()),
                ("status", models.BooleanField(default=False)),
                (
                    "locataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locataires.locataire",
                    ),
                ),
            ],
        ),
    ]
