# Generated by Django 5.0.1 on 2024-01-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batiments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batiment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
