# Generated by Django 5.0.1 on 2024-01-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Locataire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_complet", models.CharField(max_length=255)),
                ("fonction", models.CharField(max_length=255)),
                ("tel", models.IntegerField()),
                ("addresse", models.TextField(max_length=255)),
            ],
        ),
    ]
