# Generated by Django 5.0.1 on 2024-01-13 00:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locataires", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locataire",
            old_name="addresse",
            new_name="adresse",
        ),
    ]
